# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: projectrails_development
  pool: 5
  username: renaud
  password: frontier

test:
  adapter: postgresql
  encoding: unicode
  database: projectrails_test
  pool: 5
  username: renaud
  password: frontier

production:
  adapter: postgresql
  encoding: unicode
  database: projectrails_production
  pool: 5
  username: renaud
  password: frontier