# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f3ecc99b1a52e092bfdff8fcd9f41cdcd0d64b8feb3f091fa74655026ce8c068c4e00e9a825d06764387bd2860caa1232846b09ddf1301ee915ddb455d572b5

test:
  secret_key_base: 3d36f33aef4bc94efeaeede5d1357604fb94b4741c834b7a52445e2239e9c9c923005a61d706a10abf16c0246f6ebe19e8190345be0d66cb67f84ca9a805e964

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
